---

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- block:
  - name: Check for Nessus installation
    stat:
      path: "{{ nessus_install_dir }}"
    register: stat_result

  - name: Check Nessus Agent
    command: "{{ nessus_agent_check_cmd }}"
    become: yes
    changed_when: false
    ignore_errors: yes
    register: check_result

  - name: Make sure a service is running
    systemd:
      state: started
      name: "{{ nessus_agent_service_name }}"
    changed_when: false
    ignore_errors: yes
    register: nessus_agent_status

  - name: Link Nessus Agent to Nessus Manager
    command: "{{ nessus_agent_link_cmd }}"
    become: yes
    when: check_result.stdout is search('Not linked to')
  when: nessus_manage

################

#- name: Check if package is installed
#  package:
#    name: nessusagent
#    state: present
#  check_mode: true
#  register: package_check
#
#- block:
#  # Install Nessus agent for RedHat OS and CentOS
#  - include: setup-redhat.yml
#    when: (ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat")
#
#  # Install Nessus agent for Debian OS
#  - include: setup-debian.yml
#    when: ansible_os_family == 'Debian'
#  when: package_check.changed
