---
- name: Converge
  hosts: all
  become: true
  vars:
    nessus_agent_file_checksum: "md5:3eeee6531c7822ac7fe374cc28d74779"
    nessus_agent_download_url: "https://www.tenable.com/downloads/api/v1/public/pages/nessus-agents/downloads/12176/download?i_agree_to_tenable_license_agreement=true" # NessusAgent-8.2.2-es7.x86_64.rpm
    rules:
      default: accept
      plugin_reject:
        - 33851
      plugin_accept:
        - 10000-40000
      reject:
        - 10.42.123.0/24
      accept:
        - 10.0.0.0/24

  roles:
    - ansible-role-tenable-agent
